# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=10000)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('hashpw', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='traveldb',
            name='joinusers',
            field=models.ManyToManyField(related_name='travels', to='exam_app.UserDB'),
        ),
        migrations.AddField(
            model_name='traveldb',
            name='planuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.UserDB'),
        ),
    ]
